import { Component } from '@angular/core';

@Component({
  selector: 'app-positions',
  templateUrl: './positions.component.html',
  styleUrl: './positions.component.scss'
})
export class PositionsComponent {
  teams = [
    {
      name: 'Nueve Tigres',
      positions: 1,
      games: 4,
      g: 3,
      e: 1,
      p: 0,
      gf: 14,
      gc: 4,
      pts: 10,
    },
    {
      name: 'La Vision',
      positions: 2,
      games: 4,
      g: 2,
      e: 1,
      p: 1,
      gf: 12,
      gc: 7,
      pts: 7,
    },
    {
      name: 'Roy´s',
      positions: 3,
      games: 4,
      g: 2,
      e: 1,
      p: 1,
      gf: 12,
      gc: 12,
      pts: 7,
    },
    {
      name: 'Valencia',
      positions: 4,
      games: 2,
      g: 2,
      e: 0,
      p: 0,
      gf: 7,
      gc: 3,
      pts: 6,
    },
    {
      name: 'Escavioneta',
      positions: 5,
      games: 4,
      g: 2,
      e: 0,
      p: 2,
      gf: 10,
      gc: 7,
      pts: 6,
    },
    {
      name: 'U de Chile',
      positions: 6,
      games: 3,
      g: 1,
      e: 2,
      p: 0,
      gf: 5,
      gc: 4,
      pts: 5,
    },
    {
      name: 'Mosaiqueria',
      positions: 7,
      games: 4,
      g: 1,
      e: 2,
      p: 1,
      gf: 8,
      gc: 8,
      pts: 5,
    },
    {
      name: 'Sacachispa',
      positions: 8,
      games: 4,
      g: 1,
      e: 2,
      p: 1,
      gf: 7,
      gc: 9,
      pts: 5,
    },
    {
      name: 'Templarios',
      positions: 9,
      games: 3,
      g: 0,
      e: 3,
      p: 0,
      gf: 3,
      gc: 3,
      pts: 3,
    },
    {
      name: 'La Pesadilla',
      positions: 10,
      games: 4,
      g: 1,
      e: 0,
      p: 3,
      gf: 6,
      gc: 15,
      pts: 3,
    },
    {
      name: 'El Desmadre',
      positions: 11,
      games: 4,
      g: 0,
      e: 2,
      p: 2,
      gf: 7,
      gc: 13,
      pts: 2,
    },
    {
      name: 'Taller Oliosi',
      positions: 12,
      games: 4,
      g: 0,
      e: 0,
      p: 4,
      gf: 4,
      gc: 10,
      pts: 0,
    },
    
  ]
}
